#!/usr/bin/python
"""
Copyright (c) 2014, Intel Corporation

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

* Redistributions of source code must retain the above copyright notice,
  this list of conditions and the following disclaimer. 

* Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution. 

* Neither the name of Intel Corporation nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission. 

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 

@file    mobdat
@author  Mic Bowman
@date    2013-12-03

This is the main script for running the mobdat mobile data simulator.

"""

import sys, os
import logging, warnings

sys.path.append(os.path.join(os.environ.get("OPENSIM","/share/opensim"),"lib","python"))
sys.path.append(os.path.realpath(os.path.join(os.path.dirname(__file__), "..")))
sys.path.append(os.path.realpath(os.path.join(os.path.dirname(__file__), "..", "lib")))

import time, json, argparse
from mobdat.simulator import Controller

# -----------------------------------------------------------------
# -----------------------------------------------------------------
def ParseConfigurationFile(cfile) :
    try :
        config = json.load(open(cfile))
    except IOError as detail :
        warnings.warn("Error parsing configuration file %s; IO error %s" % (cfile, str(detail)))
        sys.exit(-1)
    except ValueError as detail :
        warnings.warn("Error parsing configuration file %s; value error %s" % (cfile, str(detail)))
        sys.exit(-1)
    except NameError as detail : 
        warnings.warn("Error parsing configuration file %s; name error %s" % (cfile, str(detail)))
        sys.exit(-1)
    except :
        warnings.warn('Error parsing configuration file %s; %s' % (cfile, sys.exc_info()[0]))
        sys.exit(-1)

    return config

# -----------------------------------------------------------------
# -----------------------------------------------------------------
def ParseEnvironment(config) :
    capenv = os.environ.get('OS_REMOTECONTROL_CAP')
    if capenv : 
        [capability, expires] = capenv.split(':',1)
        if expires and int(expires) > int(time.time()) :
            config["OpenSimConnector"]["Capability"] = capability

    scene = os.environ.get('OS_REMOTECONTROL_SCENE')
    if scene :
        config["OpenSimConnector"]["Scene"] = scene

    endpoint = os.environ.get('OS_REMOTECONTROL_URL')
    if endpoint :
        config["OpenSimConnector"]["EndPoint"] = endpoint

    asendpoint = os.environ.get('OS_REMOTECONTROL_UDP')
    if asendpoint :
        config["OpenSimConnector"]["AsyncEndPoint"] = asendpoint

# -----------------------------------------------------------------
# -----------------------------------------------------------------
def ParseCommandLine(config, args) :
    parser = argparse.ArgumentParser()
    
    parser.add_argument('--capability', help='capability uuid')
    parser.add_argument('--scene', help='name of the scene in which the operation is performed')
    parser.add_argument('--endpoint', help='URL of the simulator dispatcher')
    parser.add_argument('--asendpoint', help='UDP endpoint of the dispatcher')

    parser.add_argument("--interval", help="sumo interval time", type=float)
    parser.add_argument("--connectors", help="list of connectors to use in the simulation", nargs='+')

    parser.add_argument("--starttime", help="hour of the day when simulation starts", type=float)
    parser.add_argument("--secondsperstep", help="number of seconds per simulation step", type=float)

    parser.add_argument("--steps", help="number of steps to execute", type=int)

    options = parser.parse_args(args)

    if options.starttime :
        config["General"]["StartTimeOfDay"] = options.starttime
        
    if options.secondsperstep :
        config["General"]["SecondsPerStep"] = options.secondsperstep

    if options.capability :
        config["OpenSimConnector"]["Capability"] = options.capability

    if options.scene :
        config["OpenSimConnector"]["Scene"] = options.scene

    if options.endpoint :
        config["OpenSimConnector"]["EndPoint"] = options.endpoint

    if options.asendpoint :
        config["OpenSimConnector"]["AsyncEndPoint"] = options.asendpoint

    if options.steps :
        config['General']['TimeSteps'] = options.steps

    if options.interval :
        config["General"]["Interval"] = options.interval

    if options.connectors :
        config["General"]["Connectors"] = options.connectors

# -----------------------------------------------------------------
# -----------------------------------------------------------------
# def HandleWarnings(message, category, filename, lineno, file=None) :
#     mformat = 'WARNING: {0}\n'
#     sys.stderr.write(mformat.format(message))

# -----------------------------------------------------------------
# -----------------------------------------------------------------
def SetupLoggers() :
    logger = logging.getLogger()
    logger.setLevel(logging.INFO)

    logfile = filename=os.path.join(os.path.dirname(__file__), "../logs/mobdat.log")
    flog = logging.FileHandler(logfile, mode='w')
    flog.setFormatter(logging.Formatter('%(levelname)s [%(name)s] %(message)s'))
    logger.addHandler(flog)

    clog = logging.StreamHandler()
    clog.addFilter(logging.Filter(name='mobdat'))
    clog.setFormatter(logging.Formatter('[%(name)s] %(message)s'))
    clog.setLevel(logging.WARN)
    logger.addHandler(clog)

# -----------------------------------------------------------------
# -----------------------------------------------------------------
def Main() :
    SetupLoggers()

    # parse out the configuration file first
    parser = argparse.ArgumentParser()
    parser.add_argument('--config', help='configuration file for simulation settings', default='settings.js')
    (options, remainder) = parser.parse_known_args()
    
    settings = ParseConfigurationFile(options.config)
    ParseEnvironment(settings)
    ParseCommandLine(settings,remainder)

    Controller.Controller(settings)

if __name__ == '__main__':
    Main()
